# Netlify部署配置

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# 插件配置
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 环境变量（这些应该在Netlify控制台中设置）
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY

# 重定向规则 - SEO友好
# 强制HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# 删除尾部斜杠（SEO规范化）
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301

# 主页
[[redirects]]
  from = "/index"
  to = "/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Next.js路由重写
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

# Headers配置 - SEO和安全优化
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # 缓存控制
    Cache-Control = "public, max-age=0, must-revalidate"
    # Link头部 - DNS预取和资源预加载
    Link = '''</favicon.ico>; rel=preload; as=image, \
             </_next/static/css/app/layout.css>; rel=preload; as=style, \
             <https://fonts.googleapis.com>; rel=preconnect; crossorigin, \
             <https://zzyueuweeoakopuuwfau.supabase.co>; rel=preconnect'''
    
# 静态资源缓存
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 函数配置
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# 开发环境配置
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# 部署预览配置
[context.deploy-preview]
  command = "npm run build"

# 生产环境配置
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"